### ISSUE TITLE
onNodeDeselect not called

### ISSUE THREAD

**Issue by fcimaschi** [sedax90/FirJs#11]
When a node A is selected, if another node B is selected "onNodeDeselect" is not called for node A
Safari and Chrome on Mac

To reproduce, please use the provided demo with any node:

1 Select a node A
2 "onNodeSelect" is called for node A
3 Select a node B (without deselecting node A)
4 "onNodeSelect" is called for node B
5 No "onNodeDeselect" is called for node A

**Comment by sedax90** [comment]
Solved on #10
