### ISSUE TITLE
Node with long text misposition

### ISSUE THREAD

**Issue by fcimaschi** [sedax90/FirJs#6]
When a node contains a lot of text, the label has a bad positioning

Browser: Safari on Mac

<img width="986" alt="Screenshot 2023-03-30 alle 14 10 30" src="https://user-images.githubusercontent.com/71005941/229096970-9c1012ff-c6c7-4ded-94b6-41c25ba987d8.png">

**Comment by sedax90** [comment]
Solved on #14
